title: Rahul Gaba
description: My contribution to the open-source community.
author: Rahul Gaba
github: https://github.com/rgabs
about: I am a full stack developer who loves writing code for a living. I am passionate about JavaScript, VR, react-native, nodeJS, web development and Paneer.
disqus_shortname: rahulgaba
google_analytics: UA-80358007-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://facebook.com/rahulgaba16"
    - icon: fa-envelope-square
      link: "mailto:rahulgaba16@gmail.com?Subject=Hey%20there"
    - icon: fa-twitter
      link: "https://twitter.com/rahulgaba16"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/rahulgaba16"
    - icon: fa-sticky-note
      link: "/cv.pdf"
      fileName: "CV-Rahul Gaba.pdf"

share:
  twitter_username: rahulgaba16
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects and Experiments
      url: /projects/
    - text: Github
      url: https://github.com/rgabs
    - text: XML Feed
      url: /feed.xml

url: "https://rgabs.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
